-- AlterTable
ALTER TABLE "pets" ALTER COLUMN "age" SET DATA TYPE TEXT,
ALTER COLUMN "size" SET DATA TYPE TEXT,
ALTER COLUMN "energy_level" SET DATA TYPE TEXT,
ALTER COLUMN "dependency_level" SET DATA TYPE TEXT,
ALTER COLUMN "ambient" SET DATA TYPE TEXT;
